version: 2.0
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - checkout

      - run:
          command: pip install -r requirements.txt
          name: Install dependencies

#      - run: apt-get update
#      - run: apt-get install java
#
#      - run: wget -O /tmp/selenium-server-standalone-2.45.0.jar "http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar"
#
#      - run:
#          command: java -jar /tmp/selenium-server-standalone-2.45.0.jar
#          background: true

      - run:
          command: setsid python -m SimpleHTTPServer 8080
          pwd: /gordon-test/server-root
          background: true

  deploy:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run:
          command: echo "deploying! (not really) "
          pwd: /

